name: pocketshopping
description: Your shopping companion.
version: 1.1.3+5


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider:
  bottom_navigation_badge: ^1.0.3
  barcode_scan: ^2.0.1
  flutter_typeahead: ^1.8.0
  badges: ^1.1.3
  google_maps_flutter: ^0.5.30
  flutter_rating_bar: ^3.0.1+1
  camera: ^0.5.8+7
  flutter_icons: ^1.0.0+1
  image_picker: ^0.6.7+11
  google_map_polyline: ^0.2.0+1
  firebase_auth: ^0.18.1+1
  firebase_messaging: ^7.0.2
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.1+2
  cloud_functions: ^0.6.0+1
  introduction_screen: ^1.0.9
  geolocator: ^6.0.0+4
  shared_preferences: ^0.5.12
  firebase_core: ^0.5.0
  country_code_picker: ^1.3.7
  transparent_image: ^1.0.0
  image_cropper: ^1.3.1
  flux_validator_dart: ^1.0.3
  recase: ^3.0.0
  firebase_dynamic_links: ^0.6.0+1
  share: ^0.6.5+2
  rxdart: ^0.24.1
  meta: ^1.2.2
  equatable: ^1.2.4
  flutter_bloc:
    path: ./packages/flutter_bloc
  geoflutterfire: ^2.2.1
  location: ^3.0.2
  carousel_pro: ^1.0.0
  geocoder: ^0.2.1
  http: ^0.12.2
  flutter_credit_card:
    path: ./packages/flutter_credit_card
  step_progress_indicator: ^0.2.2+5
  get: ^3.12.1
  random_string: ^2.0.1
  date_format: ^1.0.9
  qr_flutter: ^3.2.0
  progress_indicators: ^0.1.5
  avatar_glow: ^1.1.0
  motion_widget: ^1.0.2
  flutter_skeleton: ^0.1.0+1
  workmanager: ^0.2.3
  flutter_local_notifications: ^2.0.0
  loadmore: ^1.0.4
  image_crop: ^0.3.2
  circular_profile_avatar: ^1.0.6
  ant_icons: ^1.0.0
  android_alarm_manager: ^0.4.5+14
  flutter_launcher_icons: ^0.7.5
  google_place: ^0.3.3
  flutter_keyboard_visibility: ^3.2.1
  url_launcher: ^5.7.2
  sliding_up_panel: ^1.0.2
  charts_flutter: ^0.9.0
  webview_flutter: ^1.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"


flutter:

  uses-material-design: true
  assets:
    - assets/images/