name: pocketshopping
description: A new Flutter application.
version: 1.0.0+1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  provider:
  bottom_navigation_badge: ^1.0.3
  barcode_scan: ^2.0.1
  flutter_typeahead: ^1.8.0
  badges: ^1.1.0
  rflutter_alert: ^1.0.2
  google_maps_flutter: ^0.5.24+1
  flutter_polyline_points: ^0.1.0
  flutter_rating_bar: ^3.0.1+1
  camera: ^0.5.7+4
  flutter_icons: ^1.0.0+1
  dash_chat: ^1.0.16
  path_provider: ^1.6.5
  image_picker: ^0.6.2+3
  google_map_polyline: ^0.2.0+1
  firebase_auth: ^0.15.5+2
  firebase_messaging: ^6.0.12
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.4.2+3
  introduction_screen: ^1.0.7
  datetime_picker_formfield: ^1.0.0
  geolocator: ^5.3.0
  shared_preferences: ^0.5.6+3
  firebase_core: ^0.4.0+9
  country_code_picker: ^1.3.7
  transparent_image: ^1.0.0
  image_cropper: ^1.2.2
  flux_validator_dart: ^1.0.3
  month_picker_dialog: ^0.3.1
  recase: ^3.0.0
  firebase_dynamic_links: ^0.5.0+11
  share: ^0.6.3+6
  rxdart: ^0.23.1
  meta: ^1.1.6
  equatable: ^1.0.0
  flutter_bloc:
    path: ./packages/flutter_bloc
  devicelocale: ^0.2.3
  geoflutterfire: ^2.1.0
  location: ^3.0.2
  carousel_pro: ^1.0.0
  geocoder: ^0.2.1
  http: ^0.12.0+4
  flutter_credit_card:
    path: ./packages/flutter_credit_card
  step_progress_indicator: ^0.2.2+5
  get: ^2.0.8-dev
  random_string: ^2.0.1
  date_format: ^1.0.8
  qr_flutter: ^3.2.0
  bubble: ^1.1.9+1
  progress_indicators: ^0.1.5
  avatar_glow: ^1.1.0
  motion_widget: ^1.0.2
  flutter_skeleton: ^0.1.0+1
  workmanager: ^0.2.3
  flutter_local_notifications: ^1.4.3
  loadmore: ^1.0.4
  image_crop: ^0.3.2
  circular_profile_avatar: ^1.0.6
  ant_icons: ^1.0.0
  android_alarm_manager: ^0.4.5+11
  flutter_launcher_icons: ^0.7.5
  google_place: ^0.3.2
  flutter_keyboard_visibility: ^3.2.1
  url_launcher: ^5.5.0
  sliding_up_panel: ^1.0.2
  flutter_ringtone_player: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"


flutter:

  uses-material-design: true
  assets:
    - assets/images/